### ISSUE TITLE
Dudas de algunas preguntas

### ISSUE THREAD

**Issue by lactunkk** [f-maldo/programming-languages#3]
10)Detalle los procesos de un compilador y un intérprete
 tengo una duda de como responder esta pregunta...

https://compiladorandrea.blogspot.com/p/proceso-de-compilacion.html  <- se espera responder algo así para esa pregunta en la parte de Compilador                                                   
o  ->  https://compiladorandrea.blogspot.com/p/fases-de-un-compilador.html

y en la parte del interprete no encontrado mas que algunas definiciones de lo que es y alguna estructuras como esta
![adfad](https://user-images.githubusercontent.com/48696647/55280492-1859f000-5305-11e9-9273-2f541b6639fa.png)

**Comment by f-maldo** [comment]
Con respecto a la primera pregunta, ambas páginas describen bien el proceso de un compilador y por lo tanto en una prueba en la que se pregunte sobre compiladores, ambas descripciones representan bien la respuesta.
Con respecto a la segunda pregunta y en general, trata de basarte en lo que aparece en la literatura publicada.
