### ISSUE TITLE
Donde encontrar información Layers

### ISSUE THREAD

**Issue by lactunkk** [f-maldo/programming-languages#4]
Que paginas me sugiere para encontrar algo relacionado con su historia y ejemplo donde se puede encontrar su estructura presente

**Comment by f-maldo** [comment]
A la rápida encontreé estas dos páginas bastante interesante: la [primera](https://www.oreilly.com/library/view/software-architecture-patterns/9781491971437/ch01.html) es principalmente un artículo que define lo que es un patrón de capas, mientras que la [segunda](http://www.openloop.com/softwareEngineering/patterns/architecturePattern/arch_Layers.htm) es como un caso de estudio. Espero que te sirvan.

**Comment by lactunkk** [comment]
Disculpe profe volver a molestar con el tema, pero tenemos complicaciones con encontrar un software que muestre que tiene este patron he estado buscando con relación a JVM, APIs y ERP pero no encuentro nada con mi compañero.
