### ISSUE TITLE
Dudas: Presentaciones de diseño

### ISSUE THREAD

**Issue by LucasRifo** [f-maldo/programming-languages#5]
En la presentación de patrones de diseño se nos pide presentar al menos 2 ejemplos de la estructura del patrón. Nuestra duda consiste en la siguiente: ¿Se nos pide gráficamente demostrar 2 ejemplos de estructura, o podemos simplemente hablar sobre la estructura?

Si fuera el segundo caso, ¿podríamos presentar en P2P algo como esto?

"Redes P2P híbridas

En este tipo de red, se puede observar la interacción entre un servidor central que sirve como Hub y administra los recursos de banda ancha, enrutamientos y comunicación entre nodos pero sin saber la identidad de cada nodo y sin almacenar información alguna, por lo que el servidor no comparte archivos de ningún tipo a ningún nodo. Tiene la peculiaridad de funcionar (en algunos casos como en Torrent) de ambas maneras, es decir, puede incorporar más de un servidor que gestione los recursos compartidos, pero también en caso de que el o los servidores que gestionan todo caigan, el grupo de nodos sigue en contacto a través de una conexión directa entre ellos mismos con lo que es posible seguir compartiendo y descargando más información en ausencia de los servidores. Este tipo de P2P sigue las siguientes características:
Tiene un servidor central que guarda información en espera y responde a peticiones para esa información.
Los nodos son responsables de hospedar la información (pues el servidor central no almacena la información), que permite al servidor central reconocer los recursos que se desean compartir, y para poder descargar esos recursos compartidos a los peers que lo solicitan.
Las terminales de enrutamiento son direcciones usadas por el servidor, que son administradas por un sistema de índices para obtener una dirección absoluta."
(http://patronesdedis.blogspot.com/2015/05/peer-to-peer.html)

**Comment by f-maldo** [comment]
Idealmente sería mostrar gráficos; de esta manera quedaría más claro. Pero con lo que describen queda bastante claro también.
