### ISSUE TITLE
Error al compilar snake.py

### ISSUE THREAD

**Issue by AlvaroDro** [f-maldo/programming-languages#8]
Hola, quería probar el programa snake.py y me salio un error de sintaxis:
`  File "snake.py", line 29
    WHITE: tuple = (255, 255, 255)
         ^
SyntaxError: invalid syntax` 

Ese error aparecia en todas las lineas de codigo que eran de está forma:
`IMAGE_PATH: str = "Images/"`
`HEAD: str = "snake_head.png"`
`BODY: str = "snake_body.png"`
`POINT: str = "snake_point.png"`
Lo cual **solucione**  así:
`IMAGE_PATH = "Images/"`
`HEAD = "snake_head.png"`
`BODY = "snake_body.png"`
`POINT = "snake_point.png"`
Mi duda es, ¿por qué me tomo la sintaxis invalida ?.
PD: Ocupo sublime text 3

**Comment by f-maldo** [comment]
Puede ser un error de la versión de Python, o porque uso pycharn
