### ISSUE TITLE
Duda de la funcion get_image() del archivo snake.py

### ISSUE THREAD

**Issue by AlvaroDro** [f-maldo/programming-languages#9]
La función get_image() en el archivo snake.py si devuelve una superficie completa de la imagen, luego está imagen ¿la puedo tratar para tomar rectángulos específicos, que vendrían a ser los sprites de los movimientos que deseo cargar?

**Comment by f-maldo** [comment]
Todavía no trabajo con el submódulo sprite, pero la función 
```
get_image()
```
devuelve un pygame.Surface

**Comment by AlvaroDro** [comment]
Si , con ese valor de retorno se puede trabajar para obtener las secuencias que necesitaba
